### ISSUE TITLE
minor: startGovernedUpgradable subsumes economicCommitteeCreatorFacet etc.

### ISSUE THREAD

**Issue by dckc** [0xpatrickdev/agoric-vault-collateral-proposal#5]
minor nit: `economicCommitteeCreatorFacet` isn't directly used by this proposal, so it's not essential here:

https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/blob/1aa1b7036c3cf349ea9fb342f1474b53d1cf0a3f/add-stATOM-oracles-permit.json#L8-L15

Likewise `contractGovernor`, I think.

But they're used indirectly via `startGovernedUpgradable`, so I suppose it doesn't hurt to reiterate them.

**Comment by dckc** [comment]
https://github.com/Agoric/agoric-sdk/commit/b414246ceb9770f3a4c1a840ca1d19c1c8ed32f4 looks like a good fix, but it seems newer than the bundles here. Care to regenerate the bundles? or at least the IDs in the README?

**Comment by dckc** [comment]
ah. now I see the updated bundles:

https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/blob/feat/statom1/README.md fef112e

**Comment by 0xpatrickdev** [comment]
In [this commit](https://github.com/Agoric/agoric-sdk/commit/b414246ceb9770f3a4c1a840ca1d19c1c8ed32f4) in [this branch](https://github.com/Agoric/agoric-sdk/compare/master...0xpatrickdev:agoric-sdk:pc/statom-vault-proposal), I removed the `economicCommitteeCreatorFacet` and `contractGovernor` powers. The build files in #11 use this fork/branch, so from our local testing it would seem things work as expected without these powers.

We can maybe mark this closed since #11 is merged in. Also can leave it open until the changes land in `agoric-sdk` via pr(s).

**Comment by dckc** [comment]
I made a separate PR for agoric-sdk: https://github.com/Agoric/agoric-sdk/pull/8226

I think this issue is best scoped to this repo, so it's fixed in #11.
